project/app/urls.py
from django.urls import path
from .views import ProductList, ProductDetail, ProductCreate, ProductEdit, ProductDelete, CategoryListView, subscribe, \
    unsubscribe

urlpatterns = [
    path('', ProductList.as_view(), name='product_list'),
    path('<int:pk>', ProductDetail.as_view(), name='product_detail'),
    path('create/', ProductCreate.as_view(), name='product_create'),
    path('<int:pk>/edit/', ProductEdit.as_view(), name='product_edit'),
    path('<int:pk>/delete/', ProductDelete.as_view(), name='product_delete'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('categories/<int:pk>/subscribe', subscribe, name='subscribe'),
    path('categories/<int:pk>/unsubscribe', unsubscribe, name='unsubscribe'),
]

project/appointment/urls.py
from django.urls import path
from .views import AppointmentView

urlpatterns = [
    path('', AppointmentView.as_view(), name='appointment')
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('app.urls')),
    path('sign/', include('sign.urls')),
    path('', include('protect.urls')),
    path('accounts/', include('allauth.urls')),
    path('appointment/', include(('appointment.urls', 'appointments'), namespace='appointment')),
]

project/templates/appoint.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width-device-width, initial-scale=1.0">
    <title>Make an Appointment</title>
</head>
<body>
    <h1>Make an Appointment</h1>
    <form action="{% url 'appointment:appointment' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="client_name">Your name</label>
        <input type="text" name="client_name"><br>
        <label for="message">Short description of your issue</label>
        <input type="text" name="message"><br>
        <label for="date">Choose time</label>
        <input type="date" name="date">.<br>
        <input type="submit">
    </form>
</body>
</html>

project/templates/category.html
{% extends 'flatpages/default.html'%}

{% block content%}
<table>
    <tr>
        <td><h3>Все Категории</h3><hr></td>
    </tr>
    {% for ct in category%}
    <tr>
        <td>{{ct.name}}</td>
        <td>
            {% if request.user in ct.subscribers.all %}
            <a href="{% url 'unsubscribe' ct.id%}">Отписаться</a>
            {% else %}
            <a href="{% url 'subscribe' ct.id%}">Подписаться</a>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock content%}

project/templates/main.html
<html>
    <head>
        <title> Simple SignUp/SignIn app</title>
    </head>
    <body>
        <div>
            <h1><a href="/">Simple SignUp/SignIn app</a></h1>
        </div>
        {% block content %}
        {% endblock %}
    </body>
</html>

project/templates/product.html
{% extends 'flatpages/default.html' %}

{% block title %}
Product
{%  endblock title %}


{% block content %}
<h2>{{product}}</h2>
{% endblock content %}

project/templates/product_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление товара</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ product.product_name }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

project/templates/product_edit.html
{% extends 'flatpages/default.html' %}


{% block content %}
<h2> Создание продукта </h2>
<hr>
<form action="" method="post">
{% csrf_token %}
{{form.as_p}}
<input type="submit" value="SAVE"/>
</form>
{% endblock content %}

project/templates/products.html
{% extends 'flatpages/default.html' %}

{% load custom_tags%}

{% block title %}
<h2>Товары</h2>j
{% endblock title%}

{% block content %}
<h2>{{ time }}</h2>
<form action="" method="get"d>
    {% csrf_token %}
    {{ filterset.form.as_p}}
    <input type="submit" value="НАЙТИ"/>
</form>
{% if products %}
<table>
        <tr>
            <td>Название</td>
            <td>Описание</td>
            <td>Категория</td>
            <td>Количество</td>
            <td>Цена</td>
        </tr>
        {% for product in products %}
        <tr>
            <td>{{product.product_name}}</td>
            <td>{{product.description|truncatechars:15}}</td>
            <td>{{product.category}}</td>
            <td>{{product.quantity}}</td>
            <td>{{product.price}}</td>
        </tr>
        {% endfor %}
</table>
{% endif %}
    {% if page_obj.has_previous  %}
        <a href="?{% url_replace page=1%}">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
        <a href="?{% url_replace page=page_obj.previous_page_number %}">{{page_obj.previous_page_number}}</a>
        {% endif %}
    {% endif %}

    {{ page_obj.number }}
    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{page_obj.next_page_number}}</a>
        {% if paginator.num_pages != page_obj.next_page_number  %}
            ...
        <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{page_obj.paginator.num_pages}}</a>
        {% endif %}
    {% endif %}

{% endblock content %}